services:
  db:
    image: docker.io/postgres:17.5
    container_name: status_monitor_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-thushima} -d ${DB_NAME:-status_monitor}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - status-monitor-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: status_monitor_app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_R2DBC_URL: ${SPRING_R2DBC_URL:-r2dbc:postgresql://db:5432/${DB_NAME}}
      SPRING_FLYWAY_URL: ${SPRING_FLYWAY_URL:-jdbc:postgresql://db:5432/${DB_NAME}}
      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET:-2a3814287a20f7f4fde6bcb2964c496df8e82be6e2482f4bd25fd51cf392330c}
      CACHE_TTL: ${CACHE_TTL:-0}
      CACHE_MAX_SIZE: ${CACHE_MAX_SIZE:-10000}
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
      LOGGING_LEVEL_APP: ${LOGGING_LEVEL_APP:-INFO}
      LOGGING_LEVEL_SPRING_WEB: ${LOGGING_LEVEL_SPRING_WEB:-INFO}
      LOGGING_LEVEL_SPRING_SECURITY: ${LOGGING_LEVEL_SPRING_SECURITY:-INFO}
      LOGGING_LEVEL_REACTOR_NETTY: ${LOGGING_LEVEL_REACTOR_NETTY:-WARN}
      LOGGING_LEVEL_HIBERNATE_SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:-DEBUG}
      LOGGING_LEVEL_HIBERNATE_TYPE: ${LOGGING_LEVEL_HIBERNATE_TYPE:-TRACE}
      LOGGING_LEVEL_SECURITY: ${LOGGING_LEVEL_SECURITY:-DEBUG}
      LOGGING_LEVEL_FLYWAY: ${LOGGING_LEVEL_FLYWAY:-DEBUG}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - status-monitor-network

networks:
  status-monitor-network:
    driver: bridge

volumes:
  postgres_data:
