spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/status_monitor
    username: thushima
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/status_monitor
    user: thushima
    password: postgres
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: 2a3814287a20f7f4fde6bcb2964c496df8e82be6e2482f4bd25fd51cf392330c
  access-token:
    expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 2592000000 # 30 days in milliseconds

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    security: DEBUG

